spring.application.name=aula

spring.web.resources.add-mappings=false
server.port=${PORT:8080}

# Configurações locais (default)
spring.datasource.url=jdbc:h2:mem:aula;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=


# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.open-in-view=false

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}

#---
spring.config.activate.on-profile=render

# Configurações para Render/PostgreSQL
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:postgres}}
spring.datasource.username=${DB_USERNAME:${JDBC_DATABASE_USERNAME:${PGUSER:postgres}}}
spring.datasource.password=${DB_PASSWORD:${JDBC_DATABASE_PASSWORD:${PGPASSWORD:postgres}}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
