spring.application.name=aula

spring.web.resources.add-mappings=false

# Configurações do datasource
spring.datasource.url=${DB_URL:jdbc:h2:mem:aula;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}


# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.open-in-view=false

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
